### ISSUE TITLE
ruby 1.9.2 compatibility

### ISSUE THREAD

**Issue by bikashp** [thoughtworks/cruisecontrol.rb#18]
Though official documentation says, CC works with 1.8.6 only but seems people are using it with higher versions also. But does it work with 1.9.2. I tried to use it but it gave following error:

``` ruby
cruise data root = '/Users/me/.cruise'
FAILED: undefined method `active_support' for #<CruiseControl::Application:0x1bdb54>
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/config/environments/add_project.rb:2:in `block in <top (required)>'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:47:in `class_eval'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:47:in `configure'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/config/environments/add_project.rb:1:in `<top (required)>'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application/bootstrap.rb:11:in `block in <module:Bootstrap>'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `run'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `block in run_initializers'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `each'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:134:in `initialize!'
    /Users/me/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/config/environment.rb:5:in `<top (required)>'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/script/add_project:69:in `require'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/script/add_project:69:in `<top (required)>'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/lib/cruise_control/init.rb:61:in `load'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/lib/cruise_control/init.rb:61:in `add'
    /Users/me/apps/thoughtworks-cruisecontrol.rb-v1.4.0-161-ga870485/thoughtworks-cruisecontrol.rb-a870485/lib/cruise_control/init.rb:12:in `run'
    ./cruise:7:in `<main>'
```

**Comment by bguthrie** [comment]
Hi bikashp - I'm currently running CC.rb master on my local machine under Ruby 1.9.2 and it's working okay for me. Can you tell me what command you executed to receive the above error? Was it ./cruise start?

**Comment by bikashp** [comment]
No, the error above was shown while adding project.
./cruise add projectname -r gitrepo -s git --trace

I'm using ruby-1.9.2-p180.

**Comment by bguthrie** [comment]
The issue appears to have been one of using incorrect load paths rather than Ruby compatibility. Please verify fix in 5308ece2963246d6bf1ef329c24fddf21733a3da if you get a chance.

**Comment by bikashp** [comment]
Thanks. That fixed my problem.
